### ISSUE TITLE
Unable to backup the data from DynamoDB to S3 bucket when the file is triggered from the scheduled event in aws lambda

### ISSUE THREAD

**Issue by ZaidMomin1** [markitx/dynamo-backup-to-s3#21]
Steps:
1. Created the aws lambda handler function.
2. Scheduled the event to backup the data 

Actual Observations :
1. When running on the single table the functions backup.on('error', function(data){});, backup.on('start-backup', function(tableName, startTime) {});, backup.on('end-backup', function(tableName, backupDuration) {}); are never executed. But when i run the same without aws lambda and handler locally im able to back up the data.
2. Function backup.backupAllTables(function() {}); is executed but no data is backed up.

Could you please provide inputs on the same.

Thanks,
Zaid

**Comment by dylanlingelbach** [comment]
Can you see if version v0.5.0 fixes this issue? There was a known issue with IAM roles running on Lambda that I just fixed

**Comment by dylanlingelbach** [comment]
Closing as 0.5.0 should fix this. Please let me know if it doesn't!
