### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by sdesalas** [markitx/dynamo-backup-to-s3#27]
At present users have to `npm install` using:

```
npm install git+https://git@github.com/markitx/dynamo-backup-to-s3.git --save
```

Would be better to have an npm package published so they can use simpler notation:

```
npm install dynamo-backup-to-s3 --save
```

**Comment by dylanlingelbach** [comment]
@sdesalas there is an NPM package published: https://www.npmjs.com/package/dynamo-backup-to-s3

Am I missing something?

**Comment by sdesalas** [comment]
Woops sorry you're right! Didnt show up on a google search for me. No other prob.

Closing ticket.
