### ISSUE TITLE
Duration calculation

### ISSUE THREAD

**Issue by mousavian** [markitx/dynamo-backup-to-s3#47]
Hi,
I am interested to know if there has been any reason behind choosing an external lib (moment-range) over using [moment's diff](https://momentjs.com/docs/#/displaying/difference/)?

If it make sense to use moment's difference, I will be happy to make a PR replacing that.

**Comment by dylanlingelbach** [comment]
A PR would be great, thanks! Just fyi, I no longer have write access to this repo. I'm trying to figure out what to do to be able to accept PRs but don't have an answer yet.

**Comment by mousavian** [comment]
Cool @dylanlingelbach, I will manage to send a PR over the weekend and once you got write access you can merge it. thanks.
