### ISSUE TITLE
maximum backup copies in s3

### ISSUE THREAD

**Issue by cg-cnu** [markitx/dynamo-backup-to-s3#54]
For our use case, 
We take a daily backup of the db, 
But we would like to limit it to maximum of 5 days. Its some non critical data, you can say 😉 
Do you guys thing it would be helpful if `dynamo-backup-to-s3` provides the functionality.
Would like to hear your thoughts 😄

**Comment by cdhowie** [comment]
@cg-cnu Can you use S3 lifecycle policies for this instead? If you set the maximum age of objects in your backup bucket to 5 days, S3 will automatically delete the older backups.

**Comment by cg-cnu** [comment]
Hey @cdhowie After a second thought I also realized its better managed from the s3 side rather than the tool. Thanks for clarifying 😄
